name: build-and-publish
on: [push]
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: 'ubuntu-latest'
    container: docker.io/library/golang:latest
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - id: build-and-publish
        run: ./hack/build.sh
